package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Destinatarios;
import com.proyecto.tesisws.modelos.DestinatariosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DestinatariosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int countByExample(DestinatariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int deleteByExample(DestinatariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int insert(Destinatarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int insertSelective(Destinatarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    List<Destinatarios> selectByExample(DestinatariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    Destinatarios selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Destinatarios record, @Param("example") DestinatariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int updateByExample(@Param("record") Destinatarios record, @Param("example") DestinatariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int updateByPrimaryKeySelective(Destinatarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table destinatarios
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    int updateByPrimaryKey(Destinatarios record);
}