package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Llaves;
import com.proyecto.tesisws.modelos.LlavesExample;
import com.proyecto.tesisws.modelos.LlavesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlavesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(LlavesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(LlavesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(LlavesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Llaves record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Llaves record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Llaves> selectByExample(LlavesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Llaves selectByPrimaryKey(LlavesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Llaves record, @Param("example") LlavesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Llaves record, @Param("example") LlavesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Llaves record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table llaves
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Llaves record);
}