package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Modelos;
import com.proyecto.tesisws.modelos.ModelosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModelosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(ModelosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(ModelosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Modelos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Modelos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Modelos> selectByExample(ModelosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Modelos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Modelos record, @Param("example") ModelosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Modelos record, @Param("example") ModelosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Modelos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Modelos record);
}