package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Sensores;
import com.proyecto.tesisws.modelos.SensoresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int countByExample(SensoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int deleteByExample(SensoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int insert(Sensores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int insertSelective(Sensores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    List<Sensores> selectByExample(SensoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    Sensores selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Sensores record, @Param("example") SensoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int updateByExample(@Param("record") Sensores record, @Param("example") SensoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int updateByPrimaryKeySelective(Sensores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensores
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    int updateByPrimaryKey(Sensores record);
}