package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Telefonos;
import com.proyecto.tesisws.modelos.TelefonosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TelefonosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(TelefonosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(TelefonosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Telefonos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Telefonos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Telefonos> selectByExample(TelefonosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Telefonos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Telefonos record, @Param("example") TelefonosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Telefonos record, @Param("example") TelefonosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Telefonos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telefonos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Telefonos record);
}