package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Tipovehiculo;
import com.proyecto.tesisws.modelos.TipovehiculoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipovehiculoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(TipovehiculoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(TipovehiculoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Tipovehiculo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Tipovehiculo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Tipovehiculo> selectByExample(TipovehiculoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Tipovehiculo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Tipovehiculo record, @Param("example") TipovehiculoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Tipovehiculo record, @Param("example") TipovehiculoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Tipovehiculo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipovehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Tipovehiculo record);
}