package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Tipomensaje;
import com.proyecto.tesisws.modelos.TipomensajeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipomensajeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(TipomensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(TipomensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Tipomensaje record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Tipomensaje record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Tipomensaje> selectByExample(TipomensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Tipomensaje selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Tipomensaje record, @Param("example") TipomensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Tipomensaje record, @Param("example") TipomensajeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Tipomensaje record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipomensaje
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Tipomensaje record);
}