package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Tipollave;
import com.proyecto.tesisws.modelos.TipollaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TipollaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(TipollaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(TipollaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Tipollave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Tipollave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Tipollave> selectByExample(TipollaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Tipollave selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Tipollave record, @Param("example") TipollaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Tipollave record, @Param("example") TipollaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Tipollave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tipollave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Tipollave record);
}