package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Usuarios;
import com.proyecto.tesisws.modelos.UsuariosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsuariosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(UsuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(UsuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Usuarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Usuarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Usuarios> selectByExample(UsuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Usuarios selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Usuarios record, @Param("example") UsuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Usuarios record, @Param("example") UsuariosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Usuarios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usuarios
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Usuarios record);
}