package com.proyecto.tesisws.dao;

import com.proyecto.tesisws.modelos.Vehiculos;
import com.proyecto.tesisws.modelos.VehiculosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VehiculosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int countByExample(VehiculosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByExample(VehiculosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insert(Vehiculos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int insertSelective(Vehiculos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    List<Vehiculos> selectByExample(VehiculosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    Vehiculos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExampleSelective(@Param("record") Vehiculos record, @Param("example") VehiculosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByExample(@Param("record") Vehiculos record, @Param("example") VehiculosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKeySelective(Vehiculos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehiculos
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    int updateByPrimaryKey(Vehiculos record);
}