package com.proyecto.tesisws.modelos;

public class Destinatarios {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.id
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.nombre
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.aPaterno
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private String aPaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.aMaterno
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private String aMaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.telefono
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.statusInvitacion
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private Integer statusInvitacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column destinatarios.idVehiculo
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private Integer idVehiculo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.id
     *
     * @return the value of destinatarios.id
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.id
     *
     * @param id the value for destinatarios.id
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.nombre
     *
     * @return the value of destinatarios.nombre
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.nombre
     *
     * @param nombre the value for destinatarios.nombre
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.aPaterno
     *
     * @return the value of destinatarios.aPaterno
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public String getaPaterno() {
        return aPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.aPaterno
     *
     * @param aPaterno the value for destinatarios.aPaterno
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setaPaterno(String aPaterno) {
        this.aPaterno = aPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.aMaterno
     *
     * @return the value of destinatarios.aMaterno
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public String getaMaterno() {
        return aMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.aMaterno
     *
     * @param aMaterno the value for destinatarios.aMaterno
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setaMaterno(String aMaterno) {
        this.aMaterno = aMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.telefono
     *
     * @return the value of destinatarios.telefono
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.telefono
     *
     * @param telefono the value for destinatarios.telefono
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.statusInvitacion
     *
     * @return the value of destinatarios.statusInvitacion
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public Integer getStatusInvitacion() {
        return statusInvitacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.statusInvitacion
     *
     * @param statusInvitacion the value for destinatarios.statusInvitacion
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setStatusInvitacion(Integer statusInvitacion) {
        this.statusInvitacion = statusInvitacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column destinatarios.idVehiculo
     *
     * @return the value of destinatarios.idVehiculo
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public Integer getIdVehiculo() {
        return idVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column destinatarios.idVehiculo
     *
     * @param idVehiculo the value for destinatarios.idVehiculo
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
}