package com.proyecto.tesisws.modelos;

import java.util.Date;

public class Historicomensajes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historicomensajes.id
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historicomensajes.mensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    private String mensaje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historicomensajes.idTipoMensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    private Integer idTipoMensaje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historicomensajes.idSubMensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    private Integer idSubMensaje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historicomensajes.fecha
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historicomensajes.idVehiculo
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    private Integer idVehiculo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historicomensajes.id
     *
     * @return the value of historicomensajes.id
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historicomensajes.id
     *
     * @param id the value for historicomensajes.id
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historicomensajes.mensaje
     *
     * @return the value of historicomensajes.mensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historicomensajes.mensaje
     *
     * @param mensaje the value for historicomensajes.mensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historicomensajes.idTipoMensaje
     *
     * @return the value of historicomensajes.idTipoMensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public Integer getIdTipoMensaje() {
        return idTipoMensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historicomensajes.idTipoMensaje
     *
     * @param idTipoMensaje the value for historicomensajes.idTipoMensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public void setIdTipoMensaje(Integer idTipoMensaje) {
        this.idTipoMensaje = idTipoMensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historicomensajes.idSubMensaje
     *
     * @return the value of historicomensajes.idSubMensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public Integer getIdSubMensaje() {
        return idSubMensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historicomensajes.idSubMensaje
     *
     * @param idSubMensaje the value for historicomensajes.idSubMensaje
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public void setIdSubMensaje(Integer idSubMensaje) {
        this.idSubMensaje = idSubMensaje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historicomensajes.fecha
     *
     * @return the value of historicomensajes.fecha
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historicomensajes.fecha
     *
     * @param fecha the value for historicomensajes.fecha
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historicomensajes.idVehiculo
     *
     * @return the value of historicomensajes.idVehiculo
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public Integer getIdVehiculo() {
        return idVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historicomensajes.idVehiculo
     *
     * @param idVehiculo the value for historicomensajes.idVehiculo
     *
     * @mbggenerated Thu Aug 20 18:16:58 CDT 2015
     */
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
}