package com.proyecto.tesisws.modelos;

public class Llaves extends LlavesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llaves.codigo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String codigo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llaves.codigo
     *
     * @return the value of llaves.codigo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llaves.codigo
     *
     * @param codigo the value for llaves.codigo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
}