package com.proyecto.tesisws.modelos;

public class LlavesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llaves.idTipoLlave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idTipoLlave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column llaves.idVehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idVehiculo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llaves.idTipoLlave
     *
     * @return the value of llaves.idTipoLlave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdTipoLlave() {
        return idTipoLlave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llaves.idTipoLlave
     *
     * @param idTipoLlave the value for llaves.idTipoLlave
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdTipoLlave(Integer idTipoLlave) {
        this.idTipoLlave = idTipoLlave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column llaves.idVehiculo
     *
     * @return the value of llaves.idVehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdVehiculo() {
        return idVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column llaves.idVehiculo
     *
     * @param idVehiculo the value for llaves.idVehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
}