package com.proyecto.tesisws.modelos;

public class Marcas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marcas.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marcas.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String nombre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marcas.id
     *
     * @return the value of marcas.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marcas.id
     *
     * @param id the value for marcas.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marcas.nombre
     *
     * @return the value of marcas.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marcas.nombre
     *
     * @param nombre the value for marcas.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}