package com.proyecto.tesisws.modelos;

public class Modelos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modelos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modelos.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modelos.idMarca
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idMarca;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modelos.id
     *
     * @return the value of modelos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modelos.id
     *
     * @param id the value for modelos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modelos.nombre
     *
     * @return the value of modelos.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modelos.nombre
     *
     * @param nombre the value for modelos.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modelos.idMarca
     *
     * @return the value of modelos.idMarca
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdMarca() {
        return idMarca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modelos.idMarca
     *
     * @param idMarca the value for modelos.idMarca
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
}