package com.proyecto.tesisws.modelos;

public class Sensores {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensores.id
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensores.sensor
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    private String sensor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensores.id
     *
     * @return the value of sensores.id
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensores.id
     *
     * @param id the value for sensores.id
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensores.sensor
     *
     * @return the value of sensores.sensor
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    public String getSensor() {
        return sensor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensores.sensor
     *
     * @param sensor the value for sensores.sensor
     *
     * @mbggenerated Mon Aug 17 17:05:55 CDT 2015
     */
    public void setSensor(String sensor) {
        this.sensor = sensor;
    }
}