package com.proyecto.tesisws.modelos;

public class Statusinvitacion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statusinvitacion.id
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statusinvitacion.status
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusinvitacion.id
     *
     * @return the value of statusinvitacion.id
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusinvitacion.id
     *
     * @param id the value for statusinvitacion.id
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column statusinvitacion.status
     *
     * @return the value of statusinvitacion.status
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column statusinvitacion.status
     *
     * @param status the value for statusinvitacion.status
     *
     * @mbggenerated Tue Aug 18 13:15:36 CDT 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}