package com.proyecto.tesisws.modelos;

public class Telefonos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefonos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefonos.telefono
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telefonos.idUsuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefonos.id
     *
     * @return the value of telefonos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefonos.id
     *
     * @param id the value for telefonos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefonos.telefono
     *
     * @return the value of telefonos.telefono
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefonos.telefono
     *
     * @param telefono the value for telefonos.telefono
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telefonos.idUsuario
     *
     * @return the value of telefonos.idUsuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telefonos.idUsuario
     *
     * @param idUsuario the value for telefonos.idUsuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
}