package com.proyecto.tesisws.modelos;

public class Tipollave {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipollave.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tipollave.tipo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String tipo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipollave.id
     *
     * @return the value of tipollave.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipollave.id
     *
     * @param id the value for tipollave.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tipollave.tipo
     *
     * @return the value of tipollave.tipo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tipollave.tipo
     *
     * @param tipo the value for tipollave.tipo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}