package com.proyecto.tesisws.modelos;

public class Usuarios {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.aPaterno
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String aPaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.aMaterno
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String aMaterno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.usuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String usuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usuarios.password
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.id
     *
     * @return the value of usuarios.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.id
     *
     * @param id the value for usuarios.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.nombre
     *
     * @return the value of usuarios.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.nombre
     *
     * @param nombre the value for usuarios.nombre
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.aPaterno
     *
     * @return the value of usuarios.aPaterno
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getaPaterno() {
        return aPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.aPaterno
     *
     * @param aPaterno the value for usuarios.aPaterno
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setaPaterno(String aPaterno) {
        this.aPaterno = aPaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.aMaterno
     *
     * @return the value of usuarios.aMaterno
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getaMaterno() {
        return aMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.aMaterno
     *
     * @param aMaterno the value for usuarios.aMaterno
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setaMaterno(String aMaterno) {
        this.aMaterno = aMaterno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.usuario
     *
     * @return the value of usuarios.usuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.usuario
     *
     * @param usuario the value for usuarios.usuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usuarios.password
     *
     * @return the value of usuarios.password
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usuarios.password
     *
     * @param password the value for usuarios.password
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }
}