package com.proyecto.tesisws.modelos;

public class Vehiculos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.placas
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String placas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.telefono
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.idUsuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idUsuario;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.idTipoVehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idTipoVehiculo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.idTipoStatus
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idTipoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehiculos.idModelo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    private Integer idModelo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.id
     *
     * @return the value of vehiculos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.id
     *
     * @param id the value for vehiculos.id
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.placas
     *
     * @return the value of vehiculos.placas
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getPlacas() {
        return placas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.placas
     *
     * @param placas the value for vehiculos.placas
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setPlacas(String placas) {
        this.placas = placas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.telefono
     *
     * @return the value of vehiculos.telefono
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.telefono
     *
     * @param telefono the value for vehiculos.telefono
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.idUsuario
     *
     * @return the value of vehiculos.idUsuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.idUsuario
     *
     * @param idUsuario the value for vehiculos.idUsuario
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.idTipoVehiculo
     *
     * @return the value of vehiculos.idTipoVehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdTipoVehiculo() {
        return idTipoVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.idTipoVehiculo
     *
     * @param idTipoVehiculo the value for vehiculos.idTipoVehiculo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdTipoVehiculo(Integer idTipoVehiculo) {
        this.idTipoVehiculo = idTipoVehiculo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.idTipoStatus
     *
     * @return the value of vehiculos.idTipoStatus
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdTipoStatus() {
        return idTipoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.idTipoStatus
     *
     * @param idTipoStatus the value for vehiculos.idTipoStatus
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdTipoStatus(Integer idTipoStatus) {
        this.idTipoStatus = idTipoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehiculos.idModelo
     *
     * @return the value of vehiculos.idModelo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public Integer getIdModelo() {
        return idModelo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehiculos.idModelo
     *
     * @param idModelo the value for vehiculos.idModelo
     *
     * @mbggenerated Sat Aug 01 13:17:37 CDT 2015
     */
    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }
}